routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Test Mongo DB view
Route::get('mongo', function(Request $request) {
    $collection = Mongo::get()->blog->posts;
    return $collection->find()->toArray();
});

// Blog 
Route::get('blog/{slug}', ['as' => 'blog.detail', 'uses' => 'BlogController@getDetail'])->where('slug', '[\w\d\-\_]+');
Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);
// Route::get('blog', 'BlogController@getIndex');

Route::get('contact', 'PagesController@getContact');
Route::get('about', 'PagesController@getAbout');

// Homepage
Route::get('/', 'PagesController@getIndex');

// Blog Posts CRUD
Route::resource('posts', 'PostController');

// Auth Routes
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home'); 

resources/views/partials/_carousel.blade.php
<div id="carousel-homepage" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    {{-- <li data-target="#carousel-example-generic" data-slide-to="2"></li> --}}
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="{{ asset('images/image1.jpg') }}" alt="">
      <div class="carousel-caption">
        <h2>Freedom defined</h2>
       <p>Fly like a gannet in the sea</p>
      </div>
    </div>
    <div class="item">
      <img src="{{ asset('images/image2.jpg') }}" alt="">
      <div class="carousel-caption">
        <h2>Sea-lfies</h2>
       <p>Best enjoyed with a mate and choice hand gestures</p>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-homepage" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-homepage" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

resources/views/partials/_footer.blade.php
      <hr>

      <p class="text-center">&copy; Keith Emmerson - No Rights Reserved at all.</p>

resources/views/partials/_head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Keith's Blog @yield('title')</title>

    <!-- Fonts -->
    <!-- <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css"> -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato|Slabo+27px" rel="stylesheet">
    {{ Html::style('css/styles.css') }}

    @yield('stylesheets')

</head>

resources/views/partials/_javascript.blade.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Optional theme -->
{{-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> --}}

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="{{ asset('js/blog.js') }}"></script>

resources/views/partials/_messages.blade.php
{{-- Display success messages --}}
@if (Session::has('success'))
	<div class="alert alert-success" role="alert">
		<i class="glyphicon glyphicon-ok"></i> <strong>Success:</strong> {{ session('success') }}
	</div>
@endif

{{-- Display error messages --}}
@if (count($errors) > 0)
	<div class="alert alert-danger" role="alert">
		<i class="glyphicon glyphicon-warning-sign"></i> <strong>Error:</strong>
		<ul>
		@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
		@endforeach
		</ul>
	</div>
@endif

resources/views/partials/_nav.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Keith&rsquo;s Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="{{ Request::is('/') ? 'active' : '' }}"><a href="/">Home <span class="sr-only">(current)</span></a></li>
        <li class="{{ Request::is('blog') ? 'active' : '' }}"><a href="/blog/">Blog</a></li>
        <li class="{{ Request::is('about') ? 'active' : '' }}"><a href="/about/">About</a></li>
        <li class="{{ Request::is('contact') ? 'active' : '' }}"><a href="/contact/">Contact</a></li>
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
        @if (Auth::check())
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hey {{ Auth::user()->name }}<span class="caret"></span></a>
          <ul class="dropdown-menu">
            
                <li><a href="{{ route('posts.index') }}">Posts</a></li>
                <li class="divider"></li>
                <li>
                    <a href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();">
                        Logout
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </li>

          </ul>
        </li>
        @else
        <li><a href="{{ route('login') }}" class="btn btn-link">Login</a></li>
        @endif
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>